version: '3.3'

services:
    stretchsms:
        image: stretchsms:latest
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        volumes: 
            - type: bind
              source: ./
              target: /stretchsms/
        command: crond -f -l 8

