version: '3.3'

services:
    stretchsms:
        image: stretchsms:latest
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        env_file:
            - .env
        volumes: 
            - type: bind
              source: ./
              target: /stretchsms/
        command: crond -f -l 8

    stretchsms-rpi:
        image: stretchsms:latest
        build:
            context: .
            dockerfile: ./docker/Dockerfile.rpi
        env_file:
            - .env
        volumes:
            - type: bind
              source: ./
              target: /stretchsms/
        command: crond -f -l 8


